// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCh3GBoxrGm1CutVyxHn_9kYcJbiDocSI',
    appId: '1:469204799605:web:f28a94bf4115244520683c',
    messagingSenderId: '469204799605',
    projectId: 'expense-manager-1fe16',
    authDomain: 'expense-manager-1fe16.firebaseapp.com',
    storageBucket: 'expense-manager-1fe16.firebasestorage.app',
    measurementId: 'G-4CQK1XBXCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8uxFjtqwbFX24sUfqNnU0rBEaauuT2kg',
    appId: '1:469204799605:android:9e20475382289ea720683c',
    messagingSenderId: '469204799605',
    projectId: 'expense-manager-1fe16',
    storageBucket: 'expense-manager-1fe16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZFsQBn7s1ANFlp4MR5q4Wwei-nFhM-zE',
    appId: '1:469204799605:ios:032d7439088c06ed20683c',
    messagingSenderId: '469204799605',
    projectId: 'expense-manager-1fe16',
    storageBucket: 'expense-manager-1fe16.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZFsQBn7s1ANFlp4MR5q4Wwei-nFhM-zE',
    appId: '1:469204799605:ios:032d7439088c06ed20683c',
    messagingSenderId: '469204799605',
    projectId: 'expense-manager-1fe16',
    storageBucket: 'expense-manager-1fe16.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCh3GBoxrGm1CutVyxHn_9kYcJbiDocSI',
    appId: '1:469204799605:web:f4d53e3d67e9f86b20683c',
    messagingSenderId: '469204799605',
    projectId: 'expense-manager-1fe16',
    authDomain: 'expense-manager-1fe16.firebaseapp.com',
    storageBucket: 'expense-manager-1fe16.firebasestorage.app',
    measurementId: 'G-15PFKB3998',
  );
}
